config/routes.rb
Rails.application.routes.draw do

  resources :used_times
  resources :goals

  resources :ut_types
  resources :tasks
  resources :otdels
  resources :priorities

  resources :users
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit',:constraints => {:format => /(json|html)/}
  post   'options/:options_page' => 'options#create'
  delete 'options/:options_page/:id' => 'options#destroy'

  post "ajax/save_last_time"
  post "ajax/save_new_otdel"
  post "ajax/save_new_task"
  post "ajax/upd_param"
  post "ajax/goal_today"
  post "ajax/goal_tomorrow"
  post "ajax/goal_sort"
  root :to => "goals#index"

end

app/models/otdel.rb
class Otdel < ActiveRecord::Base
  has_many :UsedTime
end

app/controllers/otdels_controller.rb
class OtdelsController < ApplicationController
  before_action :set_otdel, only: [:show, :edit, :update, :destroy]

  # GET /otdels
  # GET /otdels.json
  def index
    @items  = Otdel.order(:name)  
    @item = Otdel.new
  end

  # GET /otdels/1
  # GET /otdels/1.json
  def show
  end

  # GET /otdels/new
  def new
    @otdel = Otdel.new
  end

  # GET /otdels/1/edit
  def edit
  end

  # POST /otdels
  # POST /otdels.json
  def create
    @otdel = Otdel.new(otdel_params)

    respond_to do |format|
      if @otdel.save
        format.html { redirect_to otdels_url, notice: 'Otdel was successfully created.' }
        format.json { render :show, status: :created, location: @otdel }
      else
        format.html { render :new }
        format.json { render json: @otdel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /otdels/1
  # PATCH/PUT /otdels/1.json
  def update
    respond_to do |format|
      if @otdel.update(otdel_params)
        format.html { redirect_to otdels_url, notice: 'Otdel was successfully updated.' }
        format.json { render :show, status: :ok, location: @otdel }
      else
        format.html { render :edit }
        format.json { render json: @otdel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /otdels/1
  # DELETE /otdels/1.json
  def destroy
    @otdel.destroy
    respond_to do |format|
      format.html { redirect_to otdels_url, notice: 'Otdel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_otdel
      @otdel = Otdel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def otdel_params
      params.require(:otdel).permit(:name)
    end
end

app/views/otdels/_form.html.erb
<%= form_for(@otdel) do |f| %>
  <% if @otdel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@otdel.errors.count, "error") %> prohibited this otdel from being saved:</h2>

      <ul>
      <% @otdel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/otdels/edit.html.erb
<h1>Editing Otdel</h1>

<%= render 'form' %>

<%= link_to 'Show', @otdel %> |
<%= link_to 'Back', otdels_path %>

app/views/otdels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Otdels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @otdels.each do |otdel| %>
      <tr>
        <td><%= otdel.name %></td>
        <td><%= link_to 'Show', otdel %></td>
        <td><%= link_to 'Edit', edit_otdel_path(otdel) %></td>
        <td><%= link_to 'Destroy', otdel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Otdel', new_otdel_path %>

app/views/otdels/index.js.erb
$(".content").html("<%= escape_javascript(render("shared/simple_option")) %>");

app/views/otdels/new.html.erb
<h1>New Otdel</h1>

<%= render 'form' %>

<%= link_to 'Back', otdels_path %>

app/views/otdels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @otdel.name %>
</p>

<%= link_to 'Edit', edit_otdel_path(@otdel) %> |
<%= link_to 'Back', otdels_path %>