config/routes.rb
Rails.application.routes.draw do

  resources :used_times
  resources :goals

  resources :ut_types
  resources :tasks
  resources :otdels
  resources :priorities

  resources :users
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit',:constraints => {:format => /(json|html)/}
  post   'options/:options_page' => 'options#create'
  delete 'options/:options_page/:id' => 'options#destroy'

  post "ajax/save_last_time"
  post "ajax/save_new_otdel"
  post "ajax/save_new_task"
  post "ajax/upd_param"
  post "ajax/goal_today"
  post "ajax/goal_tomorrow"
  post "ajax/goal_sort"
  root :to => "goals#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
#  acts_as_avatarable
  has_many :leads
  has_many :ic_leads, foreign_key: :ic_user_id, class_name: 'Lead'
  has_many :files, class_name: 'LeadFile'
  has_many :options, class_name: 'UserOption'

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  def self.find_version_author(version)
    find(version.terminator)   
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_action :logged_in_user
#, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  
  def new
    @user = User.new
  end


  # GET /users/new
  def create
    @user = User.new(user_params)
    if @user.save
      if @user == User.first 
         @user.admin = true
         @user.save
      end
      redirect_to users_url
    else        
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Профиль обновлен"
      redirect_to users_url
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Пользователь удален"
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def user_params
      params.require(:user).permit(:name,:email, :password,
                                   :password_confirmation)
    end
    
    # Before filters
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
#      redirect_to(root_url) unless current_user?(@user)
       redirect_to(root_url) unless current_user.admin?
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/users/_user.html.erb
<li>
  <%= check_box_tag user.admin, user.admin %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<div class="hl hl_a bd">Редактировать пользователя</div>

<%= form_for(@user) do |f| %>

<div class="box_wrap box_wrap_1">
<div class="left">
  <table class="tbl_fc tbl_fc_1">
    <tr><td class="caption">E-mail:</td>
        <td><div class="inp_w"><%= f.text_field :email, class: 'form-control' %></div></td></tr>    
    <tr><td class="caption">Пароль:</td>
        <td><div class="inp_w"><%= f.password_field :password, class: 'form-control' %></div></td></tr>    

    <tr><td class="caption"></td>
      <td><%= link_to 'Отмена', users_path, :class => "sub btn_a btn_reset"%>
        <%= f.button 'Сохранить', :class => 'sub btn_a' %></td></tr>

  </table>
</div>

<% end %>
</div>

app/views/users/index.html.erb
<div class="box_wrap">
<%= link_to 'Добавить пользователя', new_user_path, class: "btn_a btn-add right" %>
</div>
<div class="sep_1"></div>

<div class="items_box_cont tbl_a">
<div class="head">Список пользователей</div>
<table class="tleads user-table">
  <thead>
    <tr>
      <th>Пользователь</th>
      <th width="60px" class="center">Админ</th>      
      <th width="30px"></th>
    </tr>
  </thead>

  <tbody>

  <!-- %= render @users %> -->
<% @users.each do |user| %>
<tr >
  <td>  <%= link_to user.email, user %> </td>
  <td class="state"><span class="check_img <%= user.admin ? "checked" :"" %>" userid="<%=user.id%>" chk="admin"></span></td>
  
  <% if is_admin? %>
     <%= edit_delete(user, current_user?(user) ? 1:nil ) %>
  <% else %>
    <td></td>
  <% end %>
  
</td>
</tr>
<% end %>

</tbody>
</table>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="signin">
<div class="hl hl_a bd">Новый пользователь</div>

 <%= form_for(@user) do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<div class="box_wrap box_wrap_1">
<div class="left">
    
  <table class="tbl_fc tbl_fc_1">
    <tr><td class="caption">E-mail:</td>
        <td><div class="inp_w"><%= f.text_field :email, class: 'form-control' %></div></td></tr>  
    <tr><td class="caption">name:</td>
        <td><div class="inp_w"><%= f.text_field :name, class: 'form-control' %></div></td></tr>      
    <tr><td class="caption">Пароль:</td>
        <td><div class="inp_w"><%= f.password_field :password, class: 'form-control' %></div></td></tr>    

	<tr><td class="caption">Подтверждение:</td>
        <td><div class="inp_w"><%= f.password_field :password_confirmation, class: 'form-control' %></div></td></tr>    

    <tr><td class="caption"></td>
      <td><%= link_to 'Отмена', users_path, :class => "sub btn_a btn_reset"%>
        <%= f.submit 'Сохранить', :class => 'sub btn_a' %></td></tr>

  </table>
</div>
</div>  

    <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>