config/routes.rb
Rails.application.routes.draw do

  resources :used_times
  resources :goals

  resources :ut_types
  resources :tasks
  resources :otdels
  resources :priorities

  resources :users
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit',:constraints => {:format => /(json|html)/}
  post   'options/:options_page' => 'options#create'
  delete 'options/:options_page/:id' => 'options#destroy'

  post "ajax/save_last_time"
  post "ajax/save_new_otdel"
  post "ajax/save_new_task"
  post "ajax/upd_param"
  post "ajax/goal_today"
  post "ajax/goal_tomorrow"
  post "ajax/goal_sort"
  root :to => "goals#index"

end

app/controllers/ut_types_controller.rb
class UtTypesController < ApplicationController

  def index
    @items  = UtType.order(:name)  
    @item = UtType.new
  end


  # POST /otdels
  # POST /otdels.json
  def create
    @ut_type = UtType.new(ut_type_params)

    respond_to do |format|
      if @ut_type.save
        format.html { redirect_to ut_types_url, notice: 'ut_type was successfully created.' }
        format.json { render :show, status: :created, location: @ut_type }
      else
        format.html { render :new }
        format.json { render json: @ut_type.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def ut_type_params
      params.require(:ut_type).permit(:name)
    end


end

app/views/ut_types/_form.html.erb
<%= form_for(@ut_type) do |f| %>
  <% if @ut_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ut_type.errors.count, "error") %> prohibited this ut_type from being saved:</h2>

      <ul>
      <% @ut_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ut_types/edit.html.erb
<h1>Editing Ut Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @ut_type %> |
<%= link_to 'Back', ut_types_path %>

app/views/ut_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ut Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ut_types.each do |ut_type| %>
      <tr>
        <td><%= ut_type.name %></td>
        <td><%= link_to 'Show', ut_type %></td>
        <td><%= link_to 'Edit', edit_ut_type_path(ut_type) %></td>
        <td><%= link_to 'Destroy', ut_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ut type', new_ut_type_path %>

app/views/ut_types/index.js.erb
$(".content").html("<%= escape_javascript(render("shared/simple_option", :locals => {a: 1} )) %>");

app/views/ut_types/new.html.erb
<h1>New Ut Type</h1>

<%= render 'form' %>

<%= link_to 'Back', ut_types_path %>

app/views/ut_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ut_type.name %>
</p>

<%= link_to 'Edit', edit_ut_type_path(@ut_type) %> |
<%= link_to 'Back', ut_types_path %>